### Read all movies with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### Read all movies with minimum duration
GET {{baseUrl}}/movies/?minimumduration=150

### Read the movie with the matching id
GET {{baseUrl}}/movies/1

### Create a new movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
  "title": "Django",
  "duration": 195,
  "budget": 162,
  "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=190918.html"
}

### Delete a movie by its id
DELETE {{baseUrl}}/movies/4

### Update the movie identified by 3
PATCH {{baseUrl}}/movies/4
Content-Type: application/json

{
  "title": "Django : Unchained",
  "duration": 195,
  "budget": 162,
  "link": "https://www.allocine.fr/film/fichefilm_gen_cfilm=190918.html"
}
